export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SEND_OTP = 'SEND_OTP'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'
